apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/tteofili/s2i-lab-trustyai"
    opendatahub.io/notebook-image-name: "Explainable Data Science"
    opendatahub.io/notebook-image-desc: "Jupyter notebook data science image with TrustyAI Explainability Library installed"
  name: s2i-generic-data-science-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.6"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"trustyai","version":"0.2.8"}]'
      openshift.io/imported-from: quay.io/tteofili/s2i-trustyai-notebook
    from:
      kind: DockerImage
      name: quay.io/tteofili/s2i-trustyai-notebook:latest
    name: "latest"
    referencePolicy:
      type: Source
